FROM rasa/rasa:3.6.21-full

USER root
WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

# Expõem porta padrão HTTP do Rasa
EXPOSE 5005

USER 1001

# Comando para rodar Rasa com API habilitada
CMD ["run", "--enable-api", "--cors", "*", "--port", "5005"]
